apiVersion: v1
kind: Service
metadata:
  name: weather-service
  labels:
    app: weather-forecast-api
    environment: dev
    tier: backend
spec:
  ports:
    - port: 8080
  selector:
    app: weather-forecast-api
    tier: backend
  type: LoadBalancer
